FROM rayproject/ray:2.9.0-py311

USER root
WORKDIR /app

# Устанавливаем дополнительные Python‑зависимости
COPY requirements_base.txt requirements_worker.txt ./
RUN pip install --no-cache-dir -r requirements_base.txt

# Копируем код вашего приложения (ml_core, workers)
COPY . .

ENV PYTHONPATH=/app

CMD ["ray", "start", "--address=ray-head:6379", "--num-cpus=4", "--block"]
